sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t setimo/docker-react-1 .

script:
  - docker run -e CI=true setimo/docker-react-1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-2-942181054496"
  bucket_path: "docker-react-1"
  on:
    branch: master
  Access_key_ID: $AWS_ACCESS_KEY
  Secret_access_key:
    secure: "$AWS_SECRET_KEY"
